"""Add new NLP columns to History

Revision ID: 7b36a9e4bdd9
Revises: 
Create Date: 2026-02-28 08:00:23.978246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b36a9e4bdd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('translated_summary', sa.Text(), nullable=True))
    op.add_column('history', sa.Column('sentiment', sa.String(length=255), nullable=True))
    op.add_column('history', sa.Column('entities', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'entities')
    op.drop_column('history', 'sentiment')
    op.drop_column('history', 'translated_summary')
    # ### end Alembic commands ###
